/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as StudentAnalyticsRouteImport } from './routes/student-analytics'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as ParentsGatewayRouteImport } from './routes/parents-gateway'
import { Route as InsightBuddyRouteImport } from './routes/insight-buddy'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as DsRouteImport } from './routes/ds'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AllearsRouteImport } from './routes/_allears'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as ParentsGatewayIndexRouteImport } from './routes/parents-gateway.index'
import { Route as FormsIndexRouteImport } from './routes/forms.index'
import { Route as DsIndexRouteImport } from './routes/ds.index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as ParentsGatewayNewRouteImport } from './routes/parents-gateway.new'
import { Route as ParentsGatewayIdRouteImport } from './routes/parents-gateway.$id'
import { Route as GlowStudentIdRouteImport } from './routes/glow.$studentId'
import { Route as FormsNewRouteImport } from './routes/forms.new'
import { Route as FormsIdRouteImport } from './routes/forms.$id'
import { Route as DsTwThemeRouteImport } from './routes/ds.tw-theme'
import { Route as DsFlowTokensRouteImport } from './routes/ds.flow-tokens'
import { Route as DsFlowComponentsRouteImport } from './routes/ds.flow-components'
import { Route as AnnouncementsIdRouteImport } from './routes/announcements.$id'
import { Route as GuestPreviewMenuRouteImport } from './routes/_guest.preview-menu'
import { Route as GuestLoginRouteImport } from './routes/_guest.login'
import { Route as AllearsAllearsRouteImport } from './routes/_allears.allears'
import { Route as AllearsAllearsIndexRouteImport } from './routes/_allears.allears.index'
import { Route as GuestReportViewTokenRouteImport } from './routes/_guest.report-view.$token'
import { Route as AllearsAllearsResponsesRouteImport } from './routes/_allears.allears.responses'
import { Route as AllearsAllearsRespondRouteImport } from './routes/_allears.allears.respond'
import { Route as AllearsAllearsQuestionsRouteImport } from './routes/_allears.allears.questions'
import { Route as AllearsAllearsIndividualsRouteImport } from './routes/_allears.allears.individuals'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentAnalyticsRoute = StudentAnalyticsRouteImport.update({
  id: '/student-analytics',
  path: '/student-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsGatewayRoute = ParentsGatewayRouteImport.update({
  id: '/parents-gateway',
  path: '/parents-gateway',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightBuddyRoute = InsightBuddyRouteImport.update({
  id: '/insight-buddy',
  path: '/insight-buddy',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const DsRoute = DsRouteImport.update({
  id: '/ds',
  path: '/ds',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AllearsRoute = AllearsRouteImport.update({
  id: '/_allears',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const ParentsGatewayIndexRoute = ParentsGatewayIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentsGatewayRoute,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormsRoute,
} as any)
const DsIndexRoute = DsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DsRoute,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const ParentsGatewayNewRoute = ParentsGatewayNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ParentsGatewayRoute,
} as any)
const ParentsGatewayIdRoute = ParentsGatewayIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ParentsGatewayRoute,
} as any)
const GlowStudentIdRoute = GlowStudentIdRouteImport.update({
  id: '/glow/$studentId',
  path: '/glow/$studentId',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsNewRoute = FormsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => FormsRoute,
} as any)
const FormsIdRoute = FormsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => FormsRoute,
} as any)
const DsTwThemeRoute = DsTwThemeRouteImport.update({
  id: '/tw-theme',
  path: '/tw-theme',
  getParentRoute: () => DsRoute,
} as any)
const DsFlowTokensRoute = DsFlowTokensRouteImport.update({
  id: '/flow-tokens',
  path: '/flow-tokens',
  getParentRoute: () => DsRoute,
} as any)
const DsFlowComponentsRoute = DsFlowComponentsRouteImport.update({
  id: '/flow-components',
  path: '/flow-components',
  getParentRoute: () => DsRoute,
} as any)
const AnnouncementsIdRoute = AnnouncementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const GuestPreviewMenuRoute = GuestPreviewMenuRouteImport.update({
  id: '/preview-menu',
  path: '/preview-menu',
  getParentRoute: () => GuestRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AllearsAllearsRoute = AllearsAllearsRouteImport.update({
  id: '/allears',
  path: '/allears',
  getParentRoute: () => AllearsRoute,
} as any)
const AllearsAllearsIndexRoute = AllearsAllearsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AllearsAllearsRoute,
} as any)
const GuestReportViewTokenRoute = GuestReportViewTokenRouteImport.update({
  id: '/report-view/$token',
  path: '/report-view/$token',
  getParentRoute: () => GuestRoute,
} as any)
const AllearsAllearsResponsesRoute = AllearsAllearsResponsesRouteImport.update({
  id: '/responses',
  path: '/responses',
  getParentRoute: () => AllearsAllearsRoute,
} as any)
const AllearsAllearsRespondRoute = AllearsAllearsRespondRouteImport.update({
  id: '/respond',
  path: '/respond',
  getParentRoute: () => AllearsAllearsRoute,
} as any)
const AllearsAllearsQuestionsRoute = AllearsAllearsQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AllearsAllearsRoute,
} as any)
const AllearsAllearsIndividualsRoute =
  AllearsAllearsIndividualsRouteImport.update({
    id: '/individuals',
    path: '/individuals',
    getParentRoute: () => AllearsAllearsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/ds': typeof DsRouteWithChildren
  '/flags': typeof FlagsRoute
  '/forms': typeof FormsRouteWithChildren
  '/insight-buddy': typeof InsightBuddyRoute
  '/parents-gateway': typeof ParentsGatewayRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/student-analytics': typeof StudentAnalyticsRoute
  '/students': typeof StudentsRouteWithChildren
  '/allears': typeof AllearsAllearsRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/preview-menu': typeof GuestPreviewMenuRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/ds/flow-components': typeof DsFlowComponentsRoute
  '/ds/flow-tokens': typeof DsFlowTokensRoute
  '/ds/tw-theme': typeof DsTwThemeRoute
  '/forms/$id': typeof FormsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/glow/$studentId': typeof GlowStudentIdRoute
  '/parents-gateway/$id': typeof ParentsGatewayIdRoute
  '/parents-gateway/new': typeof ParentsGatewayNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/ds/': typeof DsIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/parents-gateway/': typeof ParentsGatewayIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/allears/individuals': typeof AllearsAllearsIndividualsRoute
  '/allears/questions': typeof AllearsAllearsQuestionsRoute
  '/allears/respond': typeof AllearsAllearsRespondRoute
  '/allears/responses': typeof AllearsAllearsResponsesRoute
  '/report-view/$token': typeof GuestReportViewTokenRoute
  '/allears/': typeof AllearsAllearsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/flags': typeof FlagsRoute
  '/insight-buddy': typeof InsightBuddyRoute
  '/settings': typeof SettingsRoute
  '/student-analytics': typeof StudentAnalyticsRoute
  '/login': typeof GuestLoginRoute
  '/preview-menu': typeof GuestPreviewMenuRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/ds/flow-components': typeof DsFlowComponentsRoute
  '/ds/flow-tokens': typeof DsFlowTokensRoute
  '/ds/tw-theme': typeof DsTwThemeRoute
  '/forms/$id': typeof FormsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/glow/$studentId': typeof GlowStudentIdRoute
  '/parents-gateway/$id': typeof ParentsGatewayIdRoute
  '/parents-gateway/new': typeof ParentsGatewayNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/ds': typeof DsIndexRoute
  '/forms': typeof FormsIndexRoute
  '/parents-gateway': typeof ParentsGatewayIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/allears/individuals': typeof AllearsAllearsIndividualsRoute
  '/allears/questions': typeof AllearsAllearsQuestionsRoute
  '/allears/respond': typeof AllearsAllearsRespondRoute
  '/allears/responses': typeof AllearsAllearsResponsesRoute
  '/report-view/$token': typeof GuestReportViewTokenRoute
  '/allears': typeof AllearsAllearsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_allears': typeof AllearsRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/ds': typeof DsRouteWithChildren
  '/flags': typeof FlagsRoute
  '/forms': typeof FormsRouteWithChildren
  '/insight-buddy': typeof InsightBuddyRoute
  '/parents-gateway': typeof ParentsGatewayRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/student-analytics': typeof StudentAnalyticsRoute
  '/students': typeof StudentsRouteWithChildren
  '/_allears/allears': typeof AllearsAllearsRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/_guest/preview-menu': typeof GuestPreviewMenuRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/ds/flow-components': typeof DsFlowComponentsRoute
  '/ds/flow-tokens': typeof DsFlowTokensRoute
  '/ds/tw-theme': typeof DsTwThemeRoute
  '/forms/$id': typeof FormsIdRoute
  '/forms/new': typeof FormsNewRoute
  '/glow/$studentId': typeof GlowStudentIdRoute
  '/parents-gateway/$id': typeof ParentsGatewayIdRoute
  '/parents-gateway/new': typeof ParentsGatewayNewRoute
  '/reports/$id': typeof ReportsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/ds/': typeof DsIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/parents-gateway/': typeof ParentsGatewayIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/_allears/allears/individuals': typeof AllearsAllearsIndividualsRoute
  '/_allears/allears/questions': typeof AllearsAllearsQuestionsRoute
  '/_allears/allears/respond': typeof AllearsAllearsRespondRoute
  '/_allears/allears/responses': typeof AllearsAllearsResponsesRoute
  '/_guest/report-view/$token': typeof GuestReportViewTokenRoute
  '/_allears/allears/': typeof AllearsAllearsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/announcements'
    | '/ds'
    | '/flags'
    | '/forms'
    | '/insight-buddy'
    | '/parents-gateway'
    | '/reports'
    | '/settings'
    | '/student-analytics'
    | '/students'
    | '/allears'
    | '/login'
    | '/preview-menu'
    | '/announcements/$id'
    | '/ds/flow-components'
    | '/ds/flow-tokens'
    | '/ds/tw-theme'
    | '/forms/$id'
    | '/forms/new'
    | '/glow/$studentId'
    | '/parents-gateway/$id'
    | '/parents-gateway/new'
    | '/reports/$id'
    | '/students/$id'
    | '/announcements/'
    | '/ds/'
    | '/forms/'
    | '/parents-gateway/'
    | '/reports/'
    | '/students/'
    | '/allears/individuals'
    | '/allears/questions'
    | '/allears/respond'
    | '/allears/responses'
    | '/report-view/$token'
    | '/allears/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/flags'
    | '/insight-buddy'
    | '/settings'
    | '/student-analytics'
    | '/login'
    | '/preview-menu'
    | '/announcements/$id'
    | '/ds/flow-components'
    | '/ds/flow-tokens'
    | '/ds/tw-theme'
    | '/forms/$id'
    | '/forms/new'
    | '/glow/$studentId'
    | '/parents-gateway/$id'
    | '/parents-gateway/new'
    | '/reports/$id'
    | '/students/$id'
    | '/announcements'
    | '/ds'
    | '/forms'
    | '/parents-gateway'
    | '/reports'
    | '/students'
    | '/allears/individuals'
    | '/allears/questions'
    | '/allears/respond'
    | '/allears/responses'
    | '/report-view/$token'
    | '/allears'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_allears'
    | '/_guest'
    | '/announcements'
    | '/ds'
    | '/flags'
    | '/forms'
    | '/insight-buddy'
    | '/parents-gateway'
    | '/reports'
    | '/settings'
    | '/student-analytics'
    | '/students'
    | '/_allears/allears'
    | '/_guest/login'
    | '/_guest/preview-menu'
    | '/announcements/$id'
    | '/ds/flow-components'
    | '/ds/flow-tokens'
    | '/ds/tw-theme'
    | '/forms/$id'
    | '/forms/new'
    | '/glow/$studentId'
    | '/parents-gateway/$id'
    | '/parents-gateway/new'
    | '/reports/$id'
    | '/students/$id'
    | '/announcements/'
    | '/ds/'
    | '/forms/'
    | '/parents-gateway/'
    | '/reports/'
    | '/students/'
    | '/_allears/allears/individuals'
    | '/_allears/allears/questions'
    | '/_allears/allears/respond'
    | '/_allears/allears/responses'
    | '/_guest/report-view/$token'
    | '/_allears/allears/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AllearsRoute: typeof AllearsRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRouteWithChildren
  DsRoute: typeof DsRouteWithChildren
  FlagsRoute: typeof FlagsRoute
  FormsRoute: typeof FormsRouteWithChildren
  InsightBuddyRoute: typeof InsightBuddyRoute
  ParentsGatewayRoute: typeof ParentsGatewayRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  StudentAnalyticsRoute: typeof StudentAnalyticsRoute
  StudentsRoute: typeof StudentsRouteWithChildren
  GlowStudentIdRoute: typeof GlowStudentIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student-analytics': {
      id: '/student-analytics'
      path: '/student-analytics'
      fullPath: '/student-analytics'
      preLoaderRoute: typeof StudentAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents-gateway': {
      id: '/parents-gateway'
      path: '/parents-gateway'
      fullPath: '/parents-gateway'
      preLoaderRoute: typeof ParentsGatewayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insight-buddy': {
      id: '/insight-buddy'
      path: '/insight-buddy'
      fullPath: '/insight-buddy'
      preLoaderRoute: typeof InsightBuddyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ds': {
      id: '/ds'
      path: '/ds'
      fullPath: '/ds'
      preLoaderRoute: typeof DsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_allears': {
      id: '/_allears'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AllearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/parents-gateway/': {
      id: '/parents-gateway/'
      path: '/'
      fullPath: '/parents-gateway/'
      preLoaderRoute: typeof ParentsGatewayIndexRouteImport
      parentRoute: typeof ParentsGatewayRoute
    }
    '/forms/': {
      id: '/forms/'
      path: '/'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof FormsRoute
    }
    '/ds/': {
      id: '/ds/'
      path: '/'
      fullPath: '/ds/'
      preLoaderRoute: typeof DsIndexRouteImport
      parentRoute: typeof DsRoute
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/parents-gateway/new': {
      id: '/parents-gateway/new'
      path: '/new'
      fullPath: '/parents-gateway/new'
      preLoaderRoute: typeof ParentsGatewayNewRouteImport
      parentRoute: typeof ParentsGatewayRoute
    }
    '/parents-gateway/$id': {
      id: '/parents-gateway/$id'
      path: '/$id'
      fullPath: '/parents-gateway/$id'
      preLoaderRoute: typeof ParentsGatewayIdRouteImport
      parentRoute: typeof ParentsGatewayRoute
    }
    '/glow/$studentId': {
      id: '/glow/$studentId'
      path: '/glow/$studentId'
      fullPath: '/glow/$studentId'
      preLoaderRoute: typeof GlowStudentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms/new': {
      id: '/forms/new'
      path: '/new'
      fullPath: '/forms/new'
      preLoaderRoute: typeof FormsNewRouteImport
      parentRoute: typeof FormsRoute
    }
    '/forms/$id': {
      id: '/forms/$id'
      path: '/$id'
      fullPath: '/forms/$id'
      preLoaderRoute: typeof FormsIdRouteImport
      parentRoute: typeof FormsRoute
    }
    '/ds/tw-theme': {
      id: '/ds/tw-theme'
      path: '/tw-theme'
      fullPath: '/ds/tw-theme'
      preLoaderRoute: typeof DsTwThemeRouteImport
      parentRoute: typeof DsRoute
    }
    '/ds/flow-tokens': {
      id: '/ds/flow-tokens'
      path: '/flow-tokens'
      fullPath: '/ds/flow-tokens'
      preLoaderRoute: typeof DsFlowTokensRouteImport
      parentRoute: typeof DsRoute
    }
    '/ds/flow-components': {
      id: '/ds/flow-components'
      path: '/flow-components'
      fullPath: '/ds/flow-components'
      preLoaderRoute: typeof DsFlowComponentsRouteImport
      parentRoute: typeof DsRoute
    }
    '/announcements/$id': {
      id: '/announcements/$id'
      path: '/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AnnouncementsIdRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/_guest/preview-menu': {
      id: '/_guest/preview-menu'
      path: '/preview-menu'
      fullPath: '/preview-menu'
      preLoaderRoute: typeof GuestPreviewMenuRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_allears/allears': {
      id: '/_allears/allears'
      path: '/allears'
      fullPath: '/allears'
      preLoaderRoute: typeof AllearsAllearsRouteImport
      parentRoute: typeof AllearsRoute
    }
    '/_allears/allears/': {
      id: '/_allears/allears/'
      path: '/'
      fullPath: '/allears/'
      preLoaderRoute: typeof AllearsAllearsIndexRouteImport
      parentRoute: typeof AllearsAllearsRoute
    }
    '/_guest/report-view/$token': {
      id: '/_guest/report-view/$token'
      path: '/report-view/$token'
      fullPath: '/report-view/$token'
      preLoaderRoute: typeof GuestReportViewTokenRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_allears/allears/responses': {
      id: '/_allears/allears/responses'
      path: '/responses'
      fullPath: '/allears/responses'
      preLoaderRoute: typeof AllearsAllearsResponsesRouteImport
      parentRoute: typeof AllearsAllearsRoute
    }
    '/_allears/allears/respond': {
      id: '/_allears/allears/respond'
      path: '/respond'
      fullPath: '/allears/respond'
      preLoaderRoute: typeof AllearsAllearsRespondRouteImport
      parentRoute: typeof AllearsAllearsRoute
    }
    '/_allears/allears/questions': {
      id: '/_allears/allears/questions'
      path: '/questions'
      fullPath: '/allears/questions'
      preLoaderRoute: typeof AllearsAllearsQuestionsRouteImport
      parentRoute: typeof AllearsAllearsRoute
    }
    '/_allears/allears/individuals': {
      id: '/_allears/allears/individuals'
      path: '/individuals'
      fullPath: '/allears/individuals'
      preLoaderRoute: typeof AllearsAllearsIndividualsRouteImport
      parentRoute: typeof AllearsAllearsRoute
    }
  }
}

interface AllearsAllearsRouteChildren {
  AllearsAllearsIndividualsRoute: typeof AllearsAllearsIndividualsRoute
  AllearsAllearsQuestionsRoute: typeof AllearsAllearsQuestionsRoute
  AllearsAllearsRespondRoute: typeof AllearsAllearsRespondRoute
  AllearsAllearsResponsesRoute: typeof AllearsAllearsResponsesRoute
  AllearsAllearsIndexRoute: typeof AllearsAllearsIndexRoute
}

const AllearsAllearsRouteChildren: AllearsAllearsRouteChildren = {
  AllearsAllearsIndividualsRoute: AllearsAllearsIndividualsRoute,
  AllearsAllearsQuestionsRoute: AllearsAllearsQuestionsRoute,
  AllearsAllearsRespondRoute: AllearsAllearsRespondRoute,
  AllearsAllearsResponsesRoute: AllearsAllearsResponsesRoute,
  AllearsAllearsIndexRoute: AllearsAllearsIndexRoute,
}

const AllearsAllearsRouteWithChildren = AllearsAllearsRoute._addFileChildren(
  AllearsAllearsRouteChildren,
)

interface AllearsRouteChildren {
  AllearsAllearsRoute: typeof AllearsAllearsRouteWithChildren
}

const AllearsRouteChildren: AllearsRouteChildren = {
  AllearsAllearsRoute: AllearsAllearsRouteWithChildren,
}

const AllearsRouteWithChildren =
  AllearsRoute._addFileChildren(AllearsRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestPreviewMenuRoute: typeof GuestPreviewMenuRoute
  GuestReportViewTokenRoute: typeof GuestReportViewTokenRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestPreviewMenuRoute: GuestPreviewMenuRoute,
  GuestReportViewTokenRoute: GuestReportViewTokenRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface AnnouncementsRouteChildren {
  AnnouncementsIdRoute: typeof AnnouncementsIdRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
}

const AnnouncementsRouteChildren: AnnouncementsRouteChildren = {
  AnnouncementsIdRoute: AnnouncementsIdRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
}

const AnnouncementsRouteWithChildren = AnnouncementsRoute._addFileChildren(
  AnnouncementsRouteChildren,
)

interface DsRouteChildren {
  DsFlowComponentsRoute: typeof DsFlowComponentsRoute
  DsFlowTokensRoute: typeof DsFlowTokensRoute
  DsTwThemeRoute: typeof DsTwThemeRoute
  DsIndexRoute: typeof DsIndexRoute
}

const DsRouteChildren: DsRouteChildren = {
  DsFlowComponentsRoute: DsFlowComponentsRoute,
  DsFlowTokensRoute: DsFlowTokensRoute,
  DsTwThemeRoute: DsTwThemeRoute,
  DsIndexRoute: DsIndexRoute,
}

const DsRouteWithChildren = DsRoute._addFileChildren(DsRouteChildren)

interface FormsRouteChildren {
  FormsIdRoute: typeof FormsIdRoute
  FormsNewRoute: typeof FormsNewRoute
  FormsIndexRoute: typeof FormsIndexRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsIdRoute: FormsIdRoute,
  FormsNewRoute: FormsNewRoute,
  FormsIndexRoute: FormsIndexRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

interface ParentsGatewayRouteChildren {
  ParentsGatewayIdRoute: typeof ParentsGatewayIdRoute
  ParentsGatewayNewRoute: typeof ParentsGatewayNewRoute
  ParentsGatewayIndexRoute: typeof ParentsGatewayIndexRoute
}

const ParentsGatewayRouteChildren: ParentsGatewayRouteChildren = {
  ParentsGatewayIdRoute: ParentsGatewayIdRoute,
  ParentsGatewayNewRoute: ParentsGatewayNewRoute,
  ParentsGatewayIndexRoute: ParentsGatewayIndexRoute,
}

const ParentsGatewayRouteWithChildren = ParentsGatewayRoute._addFileChildren(
  ParentsGatewayRouteChildren,
)

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AllearsRoute: AllearsRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRouteWithChildren,
  DsRoute: DsRouteWithChildren,
  FlagsRoute: FlagsRoute,
  FormsRoute: FormsRouteWithChildren,
  InsightBuddyRoute: InsightBuddyRoute,
  ParentsGatewayRoute: ParentsGatewayRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  StudentAnalyticsRoute: StudentAnalyticsRoute,
  StudentsRoute: StudentsRouteWithChildren,
  GlowStudentIdRoute: GlowStudentIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
