/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as AnnouncementsIdRouteImport } from './routes/announcements.$id'
import { Route as GuestReportViewTokenRouteImport } from './routes/_guest.report-view.$token'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const AnnouncementsIdRoute = AnnouncementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const GuestReportViewTokenRoute = GuestReportViewTokenRouteImport.update({
  id: '/report-view/$token',
  path: '/report-view/$token',
  getParentRoute: () => GuestRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/flags': typeof FlagsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/report-view/$token': typeof GuestReportViewTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/flags': typeof FlagsRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/report-view/$token': typeof GuestReportViewTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_guest': typeof GuestRouteWithChildren
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/flags': typeof FlagsRoute
  '/reports': typeof ReportsRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/_guest/report-view/$token': typeof GuestReportViewTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/announcements'
    | '/flags'
    | '/reports'
    | '/students'
    | '/announcements/$id'
    | '/reports/$id'
    | '/students/$id'
    | '/announcements/'
    | '/reports/'
    | '/students/'
    | '/report-view/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/flags'
    | '/announcements/$id'
    | '/reports/$id'
    | '/students/$id'
    | '/announcements'
    | '/reports'
    | '/students'
    | '/report-view/$token'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_guest'
    | '/announcements'
    | '/flags'
    | '/reports'
    | '/students'
    | '/announcements/$id'
    | '/reports/$id'
    | '/students/$id'
    | '/announcements/'
    | '/reports/'
    | '/students/'
    | '/_guest/report-view/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  GuestRoute: typeof GuestRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRouteWithChildren
  FlagsRoute: typeof FlagsRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  StudentsRoute: typeof StudentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/announcements/$id': {
      id: '/announcements/$id'
      path: '/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AnnouncementsIdRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/_guest/report-view/$token': {
      id: '/_guest/report-view/$token'
      path: '/report-view/$token'
      fullPath: '/report-view/$token'
      preLoaderRoute: typeof GuestReportViewTokenRouteImport
      parentRoute: typeof GuestRoute
    }
  }
}

interface GuestRouteChildren {
  GuestReportViewTokenRoute: typeof GuestReportViewTokenRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestReportViewTokenRoute: GuestReportViewTokenRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface AnnouncementsRouteChildren {
  AnnouncementsIdRoute: typeof AnnouncementsIdRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
}

const AnnouncementsRouteChildren: AnnouncementsRouteChildren = {
  AnnouncementsIdRoute: AnnouncementsIdRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
}

const AnnouncementsRouteWithChildren = AnnouncementsRoute._addFileChildren(
  AnnouncementsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  GuestRoute: GuestRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRouteWithChildren,
  FlagsRoute: FlagsRoute,
  ReportsRoute: ReportsRouteWithChildren,
  StudentsRoute: StudentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
