/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudentsRouteImport } from './routes/students'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as FormsRouteImport } from './routes/forms'
import { Route as FlagsRouteImport } from './routes/flags'
import { Route as AnnouncementsRouteImport } from './routes/announcements'
import { Route as GuestRouteImport } from './routes/_guest'
import { Route as AllearsRouteImport } from './routes/_allears'
import { Route as SplatRouteImport } from './routes/$'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StudentsIndexRouteImport } from './routes/students.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as FormsIndexRouteImport } from './routes/forms.index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as StudentsIdRouteImport } from './routes/students.$id'
import { Route as ReportsIdRouteImport } from './routes/reports.$id'
import { Route as AnnouncementsIdRouteImport } from './routes/announcements.$id'
import { Route as GuestLoginRouteImport } from './routes/_guest.login'
import { Route as AllearsAllearsRouteImport } from './routes/_allears.allears'
import { Route as AllearsAllearsIndexRouteImport } from './routes/_allears.allears.index'
import { Route as GuestReportViewTokenRouteImport } from './routes/_guest.report-view.$token'
import { Route as AllearsAllearsQuestionsRouteImport } from './routes/_allears.allears.questions'

const StudentsRoute = StudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const FormsRoute = FormsRouteImport.update({
  id: '/forms',
  path: '/forms',
  getParentRoute: () => rootRouteImport,
} as any)
const FlagsRoute = FlagsRouteImport.update({
  id: '/flags',
  path: '/flags',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnouncementsRoute = AnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const GuestRoute = GuestRouteImport.update({
  id: '/_guest',
  getParentRoute: () => rootRouteImport,
} as any)
const AllearsRoute = AllearsRouteImport.update({
  id: '/_allears',
  getParentRoute: () => rootRouteImport,
} as any)
const SplatRoute = SplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsIndexRoute = StudentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const FormsIndexRoute = FormsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FormsRoute,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const StudentsIdRoute = StudentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => StudentsRoute,
} as any)
const ReportsIdRoute = ReportsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ReportsRoute,
} as any)
const AnnouncementsIdRoute = AnnouncementsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AnnouncementsRoute,
} as any)
const GuestLoginRoute = GuestLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => GuestRoute,
} as any)
const AllearsAllearsRoute = AllearsAllearsRouteImport.update({
  id: '/allears',
  path: '/allears',
  getParentRoute: () => AllearsRoute,
} as any)
const AllearsAllearsIndexRoute = AllearsAllearsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AllearsAllearsRoute,
} as any)
const GuestReportViewTokenRoute = GuestReportViewTokenRouteImport.update({
  id: '/report-view/$token',
  path: '/report-view/$token',
  getParentRoute: () => GuestRoute,
} as any)
const AllearsAllearsQuestionsRoute = AllearsAllearsQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => AllearsAllearsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/flags': typeof FlagsRoute
  '/forms': typeof FormsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/allears': typeof AllearsAllearsRouteWithChildren
  '/login': typeof GuestLoginRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/allears/questions': typeof AllearsAllearsQuestionsRoute
  '/report-view/$token': typeof GuestReportViewTokenRoute
  '/allears/': typeof AllearsAllearsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/flags': typeof FlagsRoute
  '/login': typeof GuestLoginRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/forms': typeof FormsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/students': typeof StudentsIndexRoute
  '/allears/questions': typeof AllearsAllearsQuestionsRoute
  '/report-view/$token': typeof GuestReportViewTokenRoute
  '/allears': typeof AllearsAllearsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$': typeof SplatRoute
  '/_allears': typeof AllearsRouteWithChildren
  '/_guest': typeof GuestRouteWithChildren
  '/announcements': typeof AnnouncementsRouteWithChildren
  '/flags': typeof FlagsRoute
  '/forms': typeof FormsRouteWithChildren
  '/reports': typeof ReportsRouteWithChildren
  '/students': typeof StudentsRouteWithChildren
  '/_allears/allears': typeof AllearsAllearsRouteWithChildren
  '/_guest/login': typeof GuestLoginRoute
  '/announcements/$id': typeof AnnouncementsIdRoute
  '/reports/$id': typeof ReportsIdRoute
  '/students/$id': typeof StudentsIdRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/forms/': typeof FormsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/students/': typeof StudentsIndexRoute
  '/_allears/allears/questions': typeof AllearsAllearsQuestionsRoute
  '/_guest/report-view/$token': typeof GuestReportViewTokenRoute
  '/_allears/allears/': typeof AllearsAllearsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/announcements'
    | '/flags'
    | '/forms'
    | '/reports'
    | '/students'
    | '/allears'
    | '/login'
    | '/announcements/$id'
    | '/reports/$id'
    | '/students/$id'
    | '/announcements/'
    | '/forms/'
    | '/reports/'
    | '/students/'
    | '/allears/questions'
    | '/report-view/$token'
    | '/allears/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/flags'
    | '/login'
    | '/announcements/$id'
    | '/reports/$id'
    | '/students/$id'
    | '/announcements'
    | '/forms'
    | '/reports'
    | '/students'
    | '/allears/questions'
    | '/report-view/$token'
    | '/allears'
  id:
    | '__root__'
    | '/'
    | '/$'
    | '/_allears'
    | '/_guest'
    | '/announcements'
    | '/flags'
    | '/forms'
    | '/reports'
    | '/students'
    | '/_allears/allears'
    | '/_guest/login'
    | '/announcements/$id'
    | '/reports/$id'
    | '/students/$id'
    | '/announcements/'
    | '/forms/'
    | '/reports/'
    | '/students/'
    | '/_allears/allears/questions'
    | '/_guest/report-view/$token'
    | '/_allears/allears/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SplatRoute: typeof SplatRoute
  AllearsRoute: typeof AllearsRouteWithChildren
  GuestRoute: typeof GuestRouteWithChildren
  AnnouncementsRoute: typeof AnnouncementsRouteWithChildren
  FlagsRoute: typeof FlagsRoute
  FormsRoute: typeof FormsRouteWithChildren
  ReportsRoute: typeof ReportsRouteWithChildren
  StudentsRoute: typeof StudentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/students': {
      id: '/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof StudentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forms': {
      id: '/forms'
      path: '/forms'
      fullPath: '/forms'
      preLoaderRoute: typeof FormsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flags': {
      id: '/flags'
      path: '/flags'
      fullPath: '/flags'
      preLoaderRoute: typeof FlagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/announcements': {
      id: '/announcements'
      path: '/announcements'
      fullPath: '/announcements'
      preLoaderRoute: typeof AnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_guest': {
      id: '/_guest'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof GuestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_allears': {
      id: '/_allears'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AllearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$': {
      id: '/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof SplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students/': {
      id: '/students/'
      path: '/'
      fullPath: '/students/'
      preLoaderRoute: typeof StudentsIndexRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/forms/': {
      id: '/forms/'
      path: '/'
      fullPath: '/forms/'
      preLoaderRoute: typeof FormsIndexRouteImport
      parentRoute: typeof FormsRoute
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/students/$id': {
      id: '/students/$id'
      path: '/$id'
      fullPath: '/students/$id'
      preLoaderRoute: typeof StudentsIdRouteImport
      parentRoute: typeof StudentsRoute
    }
    '/reports/$id': {
      id: '/reports/$id'
      path: '/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof ReportsIdRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/announcements/$id': {
      id: '/announcements/$id'
      path: '/$id'
      fullPath: '/announcements/$id'
      preLoaderRoute: typeof AnnouncementsIdRouteImport
      parentRoute: typeof AnnouncementsRoute
    }
    '/_guest/login': {
      id: '/_guest/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof GuestLoginRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_allears/allears': {
      id: '/_allears/allears'
      path: '/allears'
      fullPath: '/allears'
      preLoaderRoute: typeof AllearsAllearsRouteImport
      parentRoute: typeof AllearsRoute
    }
    '/_allears/allears/': {
      id: '/_allears/allears/'
      path: '/'
      fullPath: '/allears/'
      preLoaderRoute: typeof AllearsAllearsIndexRouteImport
      parentRoute: typeof AllearsAllearsRoute
    }
    '/_guest/report-view/$token': {
      id: '/_guest/report-view/$token'
      path: '/report-view/$token'
      fullPath: '/report-view/$token'
      preLoaderRoute: typeof GuestReportViewTokenRouteImport
      parentRoute: typeof GuestRoute
    }
    '/_allears/allears/questions': {
      id: '/_allears/allears/questions'
      path: '/questions'
      fullPath: '/allears/questions'
      preLoaderRoute: typeof AllearsAllearsQuestionsRouteImport
      parentRoute: typeof AllearsAllearsRoute
    }
  }
}

interface AllearsAllearsRouteChildren {
  AllearsAllearsQuestionsRoute: typeof AllearsAllearsQuestionsRoute
  AllearsAllearsIndexRoute: typeof AllearsAllearsIndexRoute
}

const AllearsAllearsRouteChildren: AllearsAllearsRouteChildren = {
  AllearsAllearsQuestionsRoute: AllearsAllearsQuestionsRoute,
  AllearsAllearsIndexRoute: AllearsAllearsIndexRoute,
}

const AllearsAllearsRouteWithChildren = AllearsAllearsRoute._addFileChildren(
  AllearsAllearsRouteChildren,
)

interface AllearsRouteChildren {
  AllearsAllearsRoute: typeof AllearsAllearsRouteWithChildren
}

const AllearsRouteChildren: AllearsRouteChildren = {
  AllearsAllearsRoute: AllearsAllearsRouteWithChildren,
}

const AllearsRouteWithChildren =
  AllearsRoute._addFileChildren(AllearsRouteChildren)

interface GuestRouteChildren {
  GuestLoginRoute: typeof GuestLoginRoute
  GuestReportViewTokenRoute: typeof GuestReportViewTokenRoute
}

const GuestRouteChildren: GuestRouteChildren = {
  GuestLoginRoute: GuestLoginRoute,
  GuestReportViewTokenRoute: GuestReportViewTokenRoute,
}

const GuestRouteWithChildren = GuestRoute._addFileChildren(GuestRouteChildren)

interface AnnouncementsRouteChildren {
  AnnouncementsIdRoute: typeof AnnouncementsIdRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
}

const AnnouncementsRouteChildren: AnnouncementsRouteChildren = {
  AnnouncementsIdRoute: AnnouncementsIdRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
}

const AnnouncementsRouteWithChildren = AnnouncementsRoute._addFileChildren(
  AnnouncementsRouteChildren,
)

interface FormsRouteChildren {
  FormsIndexRoute: typeof FormsIndexRoute
}

const FormsRouteChildren: FormsRouteChildren = {
  FormsIndexRoute: FormsIndexRoute,
}

const FormsRouteWithChildren = FormsRoute._addFileChildren(FormsRouteChildren)

interface ReportsRouteChildren {
  ReportsIdRoute: typeof ReportsIdRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIdRoute: ReportsIdRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface StudentsRouteChildren {
  StudentsIdRoute: typeof StudentsIdRoute
  StudentsIndexRoute: typeof StudentsIndexRoute
}

const StudentsRouteChildren: StudentsRouteChildren = {
  StudentsIdRoute: StudentsIdRoute,
  StudentsIndexRoute: StudentsIndexRoute,
}

const StudentsRouteWithChildren = StudentsRoute._addFileChildren(
  StudentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SplatRoute: SplatRoute,
  AllearsRoute: AllearsRouteWithChildren,
  GuestRoute: GuestRouteWithChildren,
  AnnouncementsRoute: AnnouncementsRouteWithChildren,
  FlagsRoute: FlagsRoute,
  FormsRoute: FormsRouteWithChildren,
  ReportsRoute: ReportsRouteWithChildren,
  StudentsRoute: StudentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
